In [1]:
import numpy as np
import pandas as pd

emp = {
    "id" : [1, 2, 3, 4, 5],
    "name" : ["Harnoor", "Sahil", "Aditi", "Ram", "Shyam"],
    "age" : [12, 34, 56, 78, 22],
    "Dept" : ["CSE", "ECE", "CA", "BCA", "LAW"],
    "Salary" : [12000, 78000, 45000, 66000, 33000]
    }

df = pd.DataFrame(emp)

In [ ]:
print(df.loc[3])  # get row number 3 not index

id            4
name        Ram
age          78
Dept        BCA
Salary    66000
Name: 3, dtype: object

In [4]:
print(df.loc[2,"Dept"]) # get city of 2nd rows

CA

In [5]:
print(df.loc[:,"name"])

0    Harnoor
1      Sahil
2      Aditi
3        Ram
4      Shyam
Name: name, dtype: object

In [6]:
# get multiple columns 
print(df.loc[:,["name","Salary"]])

      name  Salary
0  Harnoor   12000
1    Sahil   78000
2    Aditi   45000
3      Ram   66000
4    Shyam   33000

In [7]:
# get multiple rows 
print(df.loc[[1,2,4]])

   id   name  age Dept  Salary
1   2  Sahil   34  ECE   78000
2   3  Aditi   56   CA   45000
4   5  Shyam   22  LAW   33000

In [9]:
df.loc[df["Salary"]> 3000]

   id     name  age Dept  Salary
0   1  Harnoor   12  CSE   12000
1   2    Sahil   34  ECE   78000
2   3    Aditi   56   CA   45000
3   4      Ram   78  BCA   66000
4   5    Shyam   22  LAW   33000

In [11]:
df.loc[df["Dept"] == "CA"]

   id   name  age Dept  Salary
2   3  Aditi   56   CA   45000

In [18]:
data = {
    "product_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "name": ["Laptop", "Mouse", "Keyboard", "Monitor", "Headphones",
             "Webcam", "Printer", "USB Cable", "Speaker", "Tablet"],
    "price": [55000, 800, 1500, 12000, 2500, 1800, 9000, 400, 3500, 25000],
    "qty": [2, 10, 5, 3, 8, 4, 2, 15, 6, 3]
}
df = pd.DataFrame(data)

In [16]:
print(df)

<class 'pandas.core.frame.DataFrame'>

In [19]:
df.loc[df["price"] > 5]

   product_id        name  price  qty
0         101      Laptop  55000    2
1         102       Mouse    800   10
2         103    Keyboard   1500    5
3         104     Monitor  12000    3
4         105  Headphones   2500    8
5         106      Webcam   1800    4
6         107     Printer   9000    2
7         108   USB Cable    400   15
8         109     Speaker   3500    6
9         110      Tablet  25000    3

In [21]:
df.loc[df["qty"] < 5]

   product_id     name  price  qty
0         101   Laptop  55000    2
3         104  Monitor  12000    3
5         106   Webcam   1800    4
6         107  Printer   9000    2
9         110   Tablet  25000    3

In [23]:
df.loc[df["product_id"] == 107]

   product_id     name  price  qty
6         107  Printer   9000    2

In [24]:
df.loc[df["name"] == "Printer"]

   product_id     name  price  qty
6         107  Printer   9000    2

In [ ]:
df.loc[(df["price"] > 1800) & (df["qty"] > 4)]

   product_id        name  price  qty
4         105  Headphones   2500    8
8         109     Speaker   3500    6

In [28]:
print(df.iloc[2,3])

5

In [31]:
# get multiple records/ rows using iloc function 
df.iloc[[0,1,4]]

   product_id        name  price  qty
0         101      Laptop  55000    2
1         102       Mouse    800   10
4         105  Headphones   2500    8

In [29]:
# get first 3 recors 
print(df.iloc[0:3])

   product_id      name  price  qty
0         101    Laptop  55000    2
1         102     Mouse    800   10
2         103  Keyboard   1500    5

In [30]:
# get last record
print(df.iloc[:,-1])

0     2
1    10
2     5
3     3
4     8
5     4
6     2
7    15
8     6
9     3
Name: qty, dtype: int64

In [32]:
# get first three rows and 2 columns 
df.iloc[0:3,0:2]

   product_id      name
0         101    Laptop
1         102     Mouse
2         103  Keyboard

In [33]:
data = {
    "ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": [
        "Rahul", "Priya", "Aman", "Neha", "Arjun",
        "Rahul", "Simran", "Vikas", None, "Priya"
    ],
    "Post": [
        "Manager", "Developer", "Accountant", "HR", "Designer",
        "Developer", "Manager", None, "Accountant", "Developer"
    ],
    "Salary": [
        60000, 50000, 45000, 40000, None,
        50000, 65000, 42000, 45000, 50000
    ],
    "City": [
        "Delhi", "Mumbai", "Chandigarh", "Ludhiana", "Amritsar",
        "Mumbai", None, "Delhi", "Chandigarh", "Mumbai"
    ],
    "Age": [
        35, 28, 32, 30, 27,
        None, 38, 29, 32, 28
    ]
} 
df=pd.DataFrame(data)
df

    ID    Name        Post   Salary        City   Age
0  101   Rahul     Manager  60000.0       Delhi  35.0
1  102   Priya   Developer  50000.0      Mumbai  28.0
2  103    Aman  Accountant  45000.0  Chandigarh  32.0
3  104    Neha          HR  40000.0    Ludhiana  30.0
4  105   Arjun    Designer      NaN    Amritsar  27.0
5  106   Rahul   Developer  50000.0      Mumbai   NaN
6  107  Simran     Manager  65000.0        None  38.0
7  108   Vikas        None  42000.0       Delhi  29.0
8  109    None  Accountant  45000.0  Chandigarh  32.0
9  110   Priya   Developer  50000.0      Mumbai  28.0

In [34]:
# very important concept data preprocessing
# EDA - shape , columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      10 non-null     int64
 1   Name    9 non-null      object
 2   Post    9 non-null      object
 3   Salary  9 non-null      float64
 4   City    9 non-null      object
 5   Age     9 non-null      float64
dtypes: float64(2), int64(1), object(3)
memory usage: 612.0+ bytes

In [36]:
df.isnull()

      ID   Name   Post  Salary   City    Age
0  False  False  False   False  False  False
1  False  False  False   False  False  False
2  False  False  False   False  False  False
3  False  False  False   False  False  False
4  False  False  False    True  False  False
5  False  False  False   False  False   True
6  False  False  False   False   True  False
7  False  False   True   False  False  False
8  False   True  False   False  False  False
9  False  False  False   False  False  False

In [37]:
print(df.notnull)

<bound method DataFrame.notnull of     ID    Name        Post   Salary        City   Age
0  101   Rahul     Manager  60000.0       Delhi  35.0
1  102   Priya   Developer  50000.0      Mumbai  28.0
2  103    Aman  Accountant  45000.0  Chandigarh  32.0
3  104    Neha          HR  40000.0    Ludhiana  30.0
4  105   Arjun    Designer      NaN    Amritsar  27.0
5  106   Rahul   Developer  50000.0      Mumbai   NaN
6  107  Simran     Manager  65000.0        None  38.0
7  108   Vikas        None  42000.0       Delhi  29.0
8  109    None  Accountant  45000.0  Chandigarh  32.0
9  110   Priya   Developer  50000.0      Mumbai  28.0>

In [38]:
print(df.isnull().sum())

ID        0
Name      1
Post      1
Salary    1
City      1
Age       1
dtype: int64

In [39]:
print(df.count())

ID        10
Name       9
Post       9
Salary     9
City       9
Age        9
dtype: int64

In [43]:
df = df.fillna(0)
df

    ID    Name        Post   Salary        City   Age
0  101   Rahul     Manager  60000.0       Delhi  35.0
1  102   Priya   Developer  50000.0      Mumbai  28.0
2  103    Aman  Accountant  45000.0  Chandigarh  32.0
3  104    Neha          HR  40000.0    Ludhiana  30.0
4  105   Arjun    Designer      0.0    Amritsar  27.0
5  106   Rahul   Developer  50000.0      Mumbai   0.0
6  107  Simran     Manager  65000.0           0  38.0
7  108   Vikas           0  42000.0       Delhi  29.0
8  109       0  Accountant  45000.0  Chandigarh  32.0
9  110   Priya   Developer  50000.0      Mumbai  28.0

In [44]:
df.count()

ID        10
Name      10
Post      10
Salary    10
City      10
Age       10
dtype: int64

In [51]:
df2 = pd.read_excel('Employee.xlsx')
df2

    ID          Name                  Post  Salary       City  Age  Gender
0  101   Amit Sharma               Manager   65000      Delhi   35    Male
1  102    Neha Verma          HR Executive   42000     Mumbai   29  Female
2  103   Rahul Singh     Software Engineer   72000  Bengaluru   31    Male
3  104   Priya Gupta            Accountant   50000       Pune   28  Female
4  105   Karan Mehta       Sales Executive   39000     Jaipur   27    Male
5  106  Sneha Kapoor          Data Analyst   68000  Hyderabad   30  Female
6  107   Vikas Yadav           Team Leader   78000    Chennai   37    Male
7  108    Anjali Roy   Marketing Executive   47000    Kolkata   26  Female
8  109   Mohit Kumar  System Administrator   58000    Lucknow   33    Male
9  110  Pooja Mishra      Business Analyst   71000      Noida   32  Female

In [52]:
import pandas as pd

data = {
    "ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Product Name": ["Laptop", "Mouse", "Keyboard", "Monitor", "Printer",
                     "USB Drive", "Router", "Webcam", "Headphones", "Speaker"],
    "Price": [55000, 500, 1200, 15000, 9000, 700, 2500, 1800, 2200, 3500],
    "Quantity": [10, 50, 30, 15, 8, 100, 20, 18, 25, 12],
    "Seller Name": ["Amit Traders", "Tech World", "Digital Hub", "Screen House",
                    "Print Solutions", "Storage Mart", "Net Zone", "Vision Tech",
                    "Audio Store", "Sound Hub"],
    "Mobile": [9876543210, 9876501234, 9811122233, 9898989898, 9123456780,
               9988776655, 9090909090, 9345678901, 9765432109, 9012345678],
    "City": ["Delhi", "Mumbai", "Pune", "Bengaluru", "Chennai",
             "Hyderabad", "Kolkata", "Jaipur", "Lucknow", "Ahmedabad"]
}

df = pd.DataFrame(data)

df

    ID Product Name  Price  Quantity      Seller Name      Mobile       City
0  101       Laptop  55000        10     Amit Traders  9876543210      Delhi
1  102        Mouse    500        50       Tech World  9876501234     Mumbai
2  103     Keyboard   1200        30      Digital Hub  9811122233       Pune
3  104      Monitor  15000        15     Screen House  9898989898  Bengaluru
4  105      Printer   9000         8  Print Solutions  9123456780    Chennai
5  106    USB Drive    700       100     Storage Mart  9988776655  Hyderabad
6  107       Router   2500        20         Net Zone  9090909090    Kolkata
7  108       Webcam   1800        18      Vision Tech  9345678901     Jaipur
8  109   Headphones   2200        25      Audio Store  9765432109    Lucknow
9  110      Speaker   3500        12        Sound Hub  9012345678  Ahmedabad

In [54]:
df.iloc[0:3,0:2]

    ID Product Name
0  101       Laptop
1  102        Mouse
2  103     Keyboard

In [55]:
print(df.iloc[2:4])

    ID Product Name  Price  Quantity   Seller Name      Mobile       City
2  103     Keyboard   1200        30   Digital Hub  9811122233       Pune
3  104      Monitor  15000        15  Screen House  9898989898  Bengaluru

In [57]:
df.loc[(df["Price"] > 1500) & (df["Quantity"] > 10)]

    ID Product Name  Price  Quantity   Seller Name      Mobile       City
3  104      Monitor  15000        15  Screen House  9898989898  Bengaluru
6  107       Router   2500        20      Net Zone  9090909090    Kolkata
7  108       Webcam   1800        18   Vision Tech  9345678901     Jaipur
8  109   Headphones   2200        25   Audio Store  9765432109    Lucknow
9  110      Speaker   3500        12     Sound Hub  9012345678  Ahmedabad